; PlatformIO Project Configuration File

[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino
monitor_speed = 115200

; Large app partition is fine, keep if you already use it
board_build.partitions = huge_app.csv

; Use LittleFS
board_build.filesystem = littlefs

; Optional: put your WiFi credentials here instead of editing main.cpp
build_flags =
  -DWIFI_SSID=\"\"
  -DWIFI_PASS=\"\"

lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  esphome/AsyncTCP-esphome@^1.2.2
  esphome/ESPAsyncWebServer-esphome@^2.1.0
